require "../util/cluster"

cluster = Cluster.build :tomcat_cas do

  domain_name "local.net"

  #CAS Server
  node (:cas) {
    role :cas
    webapps "webapps_cas"
    memory 496
    ip "192.168.10.10"    
  }
  #Tomcat #1
  node (:www1) {
    role :tomcat
    webapps "webapps_www1"
    memory 496    
    ip "192.168.10.11"    
  }
  #Tomcat #2
  node (:www2) {
    role :tomcat
    webapps "webapps_www2"
    memory 496    
    ip "192.168.10.12"    
  }

end
