require "../util/cluster"

cluster = Cluster.build :tomcat_cas do
  
  domain_name "local.net"

  node (:cas) {
    role :cas
    memory 496
    webapps "webapps_cas"
  }
  node (:www1) {
    role :tomcat
    webapps "webapps_www1"
  }

end

